### ISSUE TITLE
Nachkommastellen / Decimal ending 0

### ISSUE THREAD

**Issue by 12nico07** [konik-io/konik#51]
Hallo zusammen,
Ich nutze das Konik.io SDK in meinem VB.NET Projekt. 

Problem:
Bei Kommazahlen (1.00% - 149,99€ - 99,90€) werden immer die letzten Zahlen "abgeschnitten" - sofern diese 0 sind. 

Sprich aus 99.90 wird 99.9
aus 99.00 wird 99
und 99.99 bleibt 99.99

Laut ZUGFeRD Spezifikation ist aber die Anzahl der Nachkommastellen definiert.

Beispiel:
`myTax.setPercentage(New java.math.BigDecimal("19.00"))`
(Ich habe auch versucht die Zahl als String anstatt BigDecimal zu übergeben - selber Fehler)
ergibt in der XML
`<ram:ApplicablePercent>19</ram:ApplicablePercent>`

Die ZUGFeRD Spezifikation sagt aber:
> Prozentangaben müssen nach der ZUGFeRD-Vorgabe mit 2 Nachkommastellen angegeben werden.

**Comment by Vad1mo** [comment]
Da gibt es einen parameter wie man diese Funktion ausschalten kann.  

`io.konik.stripTrailingZeros=false`

http://konik.io/docs/#konik_configuration

Ich muss noch mal nachschauen wie man es für .NET setzen kann. ich denke aber

**Comment by 12nico07** [comment]
Danke, nun funktioniert es perfekt! 

Lösung unter VB.net

`java.lang.System.setProperty("io.konik.stripTrailingZeros", "false")`
