### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by horstoeko** [konik-io/konik#56]
Hello,

i'm using iTextSharp to produce a ZUGFeRD compatible PDF document. I am only using the validator from the konik library. The validator cannot find a file inside the produced document. It throws "The PDF does not contain an attached file named ZUGFeRD-invoice.xml". I can't see any mistake done by myself, so i think there is a validor bug.

This is the file: [1432gmtx.yxt.pdf](https://github.com/konik-io/konik/files/2249491/1432gmtx.yxt.pdf)

**Comment by Vad1mo** [comment]
thx, for the report, however the pdf doesn't seem to be PDF/A compliant nor ZUGFeRD compliant.  

I suspect you should attach a file and not an ASCII Stream.

Check chapter 7.4 of the spec.

![image](https://user-images.githubusercontent.com/1492007/43651927-056145b6-9744-11e8-91f9-5fed6f5628c0.png)

![image](https://user-images.githubusercontent.com/1492007/43652006-3d9f86e0-9744-11e8-8299-ef8a03e56e01.png)

**Comment by horstoeko** [comment]
So far, I thank you for your support. I will check this. Thanks a lot

**Comment by disl** [comment]
I have the same problem. Although my ZUGFeRD file is valid (https://www.din-zugferd-validation.org), "handler.extractInvoice()" function displays the same error message.
invoice.pdf (Comfort 1.0)
[invoice.pdf](https://github.com/konik-io/konik/files/2408646/invoice.pdf)

**Comment by Vad1mo** [comment]
@disl could you post your file and sample code?

**Comment by Vad1mo** [comment]
So far there is an XMP error, 
![image](https://user-images.githubusercontent.com/1492007/45955066-3d487000-c00f-11e8-97ea-8690f36ffb86.png)

However I need to check if it impacts the extraction of the xml from the pdf.

**Comment by disl** [comment]
Thank you. I'll be waiting for your answer.

**Comment by Vad1mo** [comment]
@disl the PDF is not ZUGFeRD compliant compare the internal PDF Structure of your file with the reference.

![image](https://user-images.githubusercontent.com/1492007/45964642-a7204400-c026-11e8-838a-62678299cd3b.png)

We can adapt our lib to deal with that case, but this won't change anything in general as they are various different implementations.

**Comment by disl** [comment]
The only thing I don't understand - why file passes ZUGFeRD - test, or test methods at test are outdated or not corrected? How and where do I have to test my files?

**Comment by Vad1mo** [comment]
![image](https://user-images.githubusercontent.com/1492007/45971742-181d2700-c03a-11e8-8d63-65338672581f.png)

**Comment by Vad1mo** [comment]
apparently the just search for a file (or maybe any file) in the attachment and take it. I am not sure. 

https://www.din-zugferd-validation.org is not the official validation service as there isn't any
