### ISSUE TITLE
paymentDiscountTerm.setBasis is inaccessible due to its protection level

### ISSUE THREAD

**Issue by horstoeko** [konik-io/konik#57]
I am testing konik.io Library using .NET.<BR/>
I want to setup payment discount for an invoice. I thought I could do this with the class `PaymentDiscountTerms`:

    var paymentDiscountTerm = new PaymentDiscountTerms();
    paymentDiscountTerm.setBasis(DiscountAmount, CurrencyCode.EUR));

But this seems not possible - the compiler outputs an error message: __paymentDiscountTerm.setBasis is inaccessible due to its protection level__

What is going wrong? How is discount managed otherwise?

I made also an issue on stackoverflow: https://stackoverflow.com/questions/51725147/konik-zugferd-paymentdiscountterms

I found a similar issue at https://groups.google.com/forum/#!topic/konik-io/88z6KyQkX5U

**Comment by Vad1mo** [comment]
could you try it with this dll?

[ZUGFeRD.NET-1.3.2-NuGet.zip](https://www.dropbox.com/s/qdc7g0tvs2nukt3/ZUGFeRD.NET-1.3.2-NuGet.zip?dl=1)

**Comment by horstoeko** [comment]
Please excuse my late feedback, but I was on vacation for a long time. I can say that this version solved my problem. Can you deploy this version on NuGet? We work internally with package to resolve the corresponding references and this is an availability on NuGet necessary.

Thank you very much for your efforts

**Comment by Vad1mo** [comment]
yes its on my agenda to update the NuGet, but its not yet automated.

**Comment by Vad1mo** [comment]
@GregorGlinka both versions of the lib don't do any pdf to pdf/a3 conversation. 
The old version didn't check if the provided PDF is PDF-A compliant. While it appeared that everything works, in reality the files weren't ZUGFeRD complaint, which is a bug IMHO.

The new version does that check and stops if the PDF provided is a plain PDF.
