### ISSUE TITLE
ZUGFeRD 2.0

### ISSUE THREAD

**Issue by horstoeko** [konik-io/konik#58]
Hi.

I have the following question: When is it to be expected that "konik" will also support the "ZUGFeRD 2.0" format adapted to the European standard? Currently, in my opinion, only the possibility to export in the "old" ZUGFeRD 1.0 format.

**Comment by Vad1mo** [comment]
Konik 2.0 will be released when ZUGFeRD 2.0 is officially realised.

**Comment by horstoeko** [comment]
Will it be also available for the .NET Implementation?

**Comment by Vad1mo** [comment]
definitely.

**Comment by Indigo744** [comment]
Hello,

While ZUGFeRD 2.0/FacturX is still not "officially" released, it's format is publicly available and should not change _that_ much. As a matter of fact, the French administration started to support the FacturX format for B2G invoicing.

Do you have any information on the current implementation of ZUGFeRD 2.0 in Konik? Do you have any estimation on a release date or something?

Thanks.

**Comment by horstoeko** [comment]
It has been many months now. In my opinion, version 2.0 is now released. When is it likely that a new version of this great library will be released?

**Comment by Indigo744** [comment]
For what is worth, I gave up waiting on Konik and went with [Mustang](https://github.com/ZUGFeRD/mustangproject), since we are now (in 2019) obliged to use electronic invoicing for B2G in France.

**Comment by horstoeko** [comment]
> 
> 
> For what is worth, I gave up waiting on Konik and went with [Mustang](https://github.com/ZUGFeRD/mustangproject), since we are now (in 2019) obliged to use electronic invoicing for B2G in France.

Unfortunately, I have the same problem. Unfortunately, the Mustang project is eliminated, as there is no .NET implementation. We are Navision partners and rely on .NET components.

**Comment by Indigo744** [comment]
> 
> 
> > For what is worth, I gave up waiting on Konik and went with [Mustang](https://github.com/ZUGFeRD/mustangproject), since we are now (in 2019) obliged to use electronic invoicing for B2G in France.
> 
> Unfortunately, I have the same problem. Unfortunately, the Mustang project is eliminated, as there is no .NET implementation. We are Navision partners and rely on .NET components.

Kinda same issue, would have preferred a .Net component. But we still went with it using command line (our software actually fires up java with Mustang, passing all needed params such as input pdf and xml, wait for its return and read the new pdf created). Slower, sure. But it works.

**Comment by horstoeko** [comment]
> 
> 
> > > For what is worth, I gave up waiting on Konik and went with [Mustang](https://github.com/ZUGFeRD/mustangproject), since we are now (in 2019) obliged to use electronic invoicing for B2G in France.
> > 
> > 
> > Unfortunately, I have the same problem. Unfortunately, the Mustang project is eliminated, as there is no .NET implementation. We are Navision partners and rely on .NET components.
> 
> Kinda same issue, would have preferred a .Net component. But we still went with it using command line (our software actually fires up java with Mustang, passing all needed params such as input pdf and xml, wait for its return and read the new pdf created). Slower, sure. But it works.
> 
> Edit:
> I spoke too fast. We have actually a more complicated pipeline:
> First, our ERP emits a simple PDF (A/3) and an XML (compatible FacturX) in a specific folder.
> A Powershell script in our server watch this folder. When it detects new files, it takes them and merge them using Mustang (with command line) in another folder.
> This allows us to avoid deploying Java to every client using the ERP. Only the server has Java and perform the merging.

That's certainly a possibility. Unfortunately, we have no JAVA skills in the company, so this procedure is unfortunately out of the question for us.
Question: Which library do you use to create the XML?

**Comment by Indigo744** [comment]
> 
> That's certainly a possibility. Unfortunately, we have no JAVA skills in the company, so this procedure is unfortunately out of the question for us.
> Question: Which library do you use to create the XML?

Actually, you don't even need to know Java. Here is how we generate a FacturX from a PDF and an XML:
```
java -jar mustang.jar --combine --source "my.pdf" --source-xml "my.xml" --zugferd-version 2 --zugferd-profile E --out "facturx.pdf"
```

As for the XML part... Well this is the hardest part. We had to develop a module to generate it by hand (taking value directly from the DB).

**Comment by horstoeko** [comment]
> 
> 
> > That's certainly a possibility. Unfortunately, we have no JAVA skills in the company, so this procedure is unfortunately out of the question for us.
> > Question: Which library do you use to create the XML?
> 
> Actually, you don't even need to know Java. Here is how we generate a FacturX from a PDF and an XML:
> 
> ```
> java -jar mustang.jar --combine --source "my.pdf" --source-xml "my.xml" --zugferd-version 2 --zugferd-profile E --out "facturx.pdf"
> ```
> 
> As for the XML part... Well this is the hardest part. We had to develop a module to generate it by hand (taking value directly from the DB).

Ah okay. Thanks for the information. My plan would be based on an XSD (XRechnung, etc.) to generate the appropriate classes automatically. Only I can not find an XSD.

**Comment by Indigo744** [comment]
> 
> Ah okay. Thanks for the information. My plan would be based on an XSD (XRechnung, etc.) to generate the appropriate classes automatically. Only I can not find an XSD.

We use XSD to validate our XML generated. We found them here: http://fnfe-mpe.org/factur-x/factur-x_en/ (at the bottom, there are a lot of files, including example and XSD).

**Comment by horstoeko** [comment]
> 
> 
> > Ah okay. Thanks for the information. My plan would be based on an XSD (XRechnung, etc.) to generate the appropriate classes automatically. Only I can not find an XSD.
> 
> We use XSD to validate our XML generated. We found them here: http://fnfe-mpe.org/factur-x/factur-x_en/ (at the bottom, there are a lot of files, including example and XSD).

Okay so far. I will have a look on this page. Much thanks.

**Comment by murygin** [comment]
Are there any plans to release a version that supports ZUGFeRD 2.x and if so, when will this version be released?

**Comment by Vad1mo** [comment]
Yes it is planned.
