### ISSUE TITLE
"TotalAllowanceChargeAmount" should not be used within "SpecifiedTradeSettlementMonetarySummation"

### ISSUE THREAD

**Issue by markose** [konik-io/konik#59]
Hello.

First of all thank you very much for this great library. It works like a charm!

There seems to be one thing, that does not conform with the specification.

According to them "TotalAllowanceChargeAmount" should not be used within "SpecifiedTradeSettlementMonetarySummation". 

That's at least what the validator (https://www.din-zugferd-validation.org) says.

See also the specification:
![image](https://user-images.githubusercontent.com/2076084/44918576-9dfbca00-ad3b-11e8-9129-8fd49d13993a.png)

I've not set any charges. The "TotalAllowanceChargeAmount" seems to be generated by the library.
Another thing they complain is, that it should have 4 fractional digits instead of two.

**Comment by Vad1mo** [comment]
the din-zugferd-validation.org is not correct in many cases:
However I'll check regarding _"TotalAllowanceChargeAmount" should not be used within "SpecifiedTradeSettlementMonetarySummation"._
