### ISSUE TITLE
Specific enums for codes like TaxRegistration

### ISSUE THREAD

**Issue by djmj** [konik-io/konik#62]
A lot of things are straightforward to programm and very intuitive. But finding the tax registration type code was not since it is included in the big code list of class _Reference_. 

Here some examples which would make code more user friendly and programming less error prone.

**TaxRegistrationCode**

This would be more user friendly if a specific enum would be created only consisting of the two possible values (FN, VAT).

**Note**

SubjectCode

**SchemeID**

Same applies to the small set of global id types for an _Item_ like _GTIN_. Its just not nice having a String like _"0160"_ in code that defines it.

**Comment by Vad1mo** [comment]
could give a code example how it might look like? I have some difficulties to visualize this.

**Comment by djmj** [comment]
Something like

	public enum TaxRegistrationCode
	{
		VAT,
		FC
	}

	new TaxRegistration("DE...", TaxRegistrationCode.VAT);
