### ISSUE TITLE
Define currency global

### ISSUE THREAD

**Issue by djmj** [konik-io/konik#63]
It feels a little cumbersome to repeat the same code in many places (item, sum, tax) like:

	final MonetarySummation sum = new MonetarySummation();
	sum.setLineTotal(new Amount(lineTotal, CurrencyCode.EUR));
	sum.setChargeTotal(new Amount(chargeTotal, CurrencyCode.EUR));

This approach would reduce code and make it more readable:

	final MonetarySummation sum = new MonetarySummation(CurrencyCode.EUR);
	sum.setLineTotal(lineTotal);
	sum.setChargeTotal(chargeTotal);

Defining the currency on _Invoice_ level would be the most elegant solution.

**Comment by Vad1mo** [comment]
This would break the API, but its a nice concept. 

Before approving the change, We need to make sure that an Invoice must have only one currency.

This would be something for 2.0
