### ISSUE TITLE
Define default date pattern

### ISSUE THREAD

**Issue by djmj** [konik-io/konik#64]
A konic beginner will try to set a Date intuitive and fail little confused like:

	Date issued = myInvoice.issued;
	header.setIssued(issued);

but must create a spefific Zf instance:

	header.setIssued(new ZfDateDay(issued));

There are certain date formats of zugferd this _Zf_ structure supports. Allowing java _Date_ could be archived by overloading the function which does the conversion internally.

**Comment by Vad1mo** [comment]
ZfDate is subclass of Date already.

ZfDate is mandatory as  ZF Dates have a format.  There are already Classes for the typical usecases e.g. ZfDateDay

there is even a ZfDateFactory that produces ZfDate for each CODE

Can you provide an example:

**Comment by djmj** [comment]
The idea was to allow _Date_ as argument instead of _ZfDate_ since i dont care what format zugferd uses internal. Something flexible like:

	public class Header
	{
		public void setIssued(Date issued)
		{
			this.issued = ZfDate.convertTo(issued);
		}

		public static ZfDate convertTo(Date date)
		{
			if (date instanceof ZfDate)
				return (ZfDate)date;
			else
				return new ZfDateDay(date);
		}
	}

In this case the default will be converted to _ZfDateDay_. 

Further the application could provide a "default date converter" interface which could be used, in case a different default format shall be used. If this is necessary.

	public Invoice(ZfDateConverter dateConverter)
