### ISSUE TITLE
Payment in PaymentDiscountTerms can not be assigned with correct precision

### ISSUE THREAD

**Issue by AchuThanFinstreet** [konik-io/konik#66]
I am trying to use a 4-digit-precision-amount to PaymentDiscountTerm.setBasis() on my extended-profile-invoice.
Nevertheless the xml-data of the created pdf will contain a 2-digit Number. 
This is the error-message in "www.din-zugferd-validation.org":
`Preise und Zwischenwerte bei der Rabattberechnung müssen nach der ZUGFeRD-Vorgabe mit 4 Nachkommastellen angegeben werden.`
So we must use here 4-digit precision according to ZUGFeRD-specification.

This is how I tried to create the Amount-Object in Kotlin:

`Amount(BigDecimal.valueOf(value).setScale(4, RoundingMode.HALF_UP), CurrencyCode.getByCode(currency))`

Konik-configs have this set:
`
io.konik.jaxb.adapter.TwoDigitRoundingAdapter.scale=2
io.konik.jaxb.adapter.TwoDigitRoundingAdapter.roundingMode=HALF_UP
io.konik.jaxb.adapter.FourDigitRoundingAdapter.scale=4
io.konik.jaxb.adapter.FourDigitRoundingAdapter.roundingMode=HALF_UP
`

We can't create a valid invoice-pdf with a discount in EXTENDED-profile or am I missing something?

**Comment by Vad1mo** [comment]
1943 6.6.2 Decimal points
1944 Amounts are shown to two decimal places and are rounded where necessary (e.g. 15.00).
1945 VAT rates are stated as percentages with maximum 2 decimals. E.g. twenty one and one third percent is
1946 stated as 21.33. Quantities are shown to four decimal places (e.g. 1.0000).
1947 Prices and interim values in the calculation of the discount are shown to four decimal places (e.g. 0.6667).

**Comment by AchuThanFinstreet** [comment]
since this is about the class PaymentDiscountTerm, the line 1947 should apply, but currently the definition of line 1944 is used. So this is why the validation of "www.din-zugferd-validation.org" is complaining.
