### ISSUE TITLE
HeaderExchangedDocument - IssueDateTime - is missing

### ISSUE THREAD

**Issue by Hopfenspirger** [konik-io/konik#67]
Hello, 

I have the ZUGFeRD XML below and want to read the IssueDateTime with the following code but it returns null on .getIssued(). The XML was created with konik - according to my customer. 

Do I do something wrong or is this a bug?

Code:
```
            var handler = new PdfHandler();
            using (InputStream inputZugferdPdfStream = new FileInputStream(pdfFileName)) {
                var invoice = handler.extractInvoice(inputZugferdPdfStream);
                var header = invoice.getHeader();
                if (!string.IsNullOrWhiteSpace(header?.getIssued()?.toString())) {
                    var rechnungsDatum = DateTime.Parse(header?.getIssued()?.toString());
                }
```

XML:
```
	<rsm:HeaderExchangedDocument>
		<ram:ID>7063111335</ram:ID>
		<ram:Name>Sammelrechnung</ram:Name>
		<ram:TypeCode>380</ram:TypeCode>
		<ram:IssueDateTime>
			<udt:DateTimeString format="102">20190122</udt:DateTimeString>
		</ram:IssueDateTime>
```

**Comment by Vad1mo** [comment]
can you paste the `xml`?  you can also send the file to <hello(at)konik.io>

**Comment by Hopfenspirger** [comment]
The mail to <hello(at)konik.io> with the xml attached was rejected by google mail. The XML contains confidential content so I don't want to post it here. I try to zip it first and resend it...
