### ISSUE TITLE
Change ProfileVersion to 1.0

### ISSUE THREAD

**Issue by oledede** [konik-io/konik#69]
Hello,
I need to change the line "<zf: version> 1p0 </ zf: version>" to "<zf: version> 1.0 </ zf: version>".

Otherwise the files can not be imported. How can I change this?

**Comment by Vad1mo** [comment]
why as `1p0` is the correct one according to the spec

**Comment by oledede** [comment]
The software TAIFUN unfortunately can not import this.

They only want 1.0, otherwise it will not work.

**Comment by oledede** [comment]
It must be really there 1.0.

**Comment by Vad1mo** [comment]
Just to make sure we understand each other you are referring to the XMP Metadata extension of the PDF/A. Am I right?


![image](https://user-images.githubusercontent.com/1492007/55877661-ebc29580-5b9a-11e9-87cc-5fcd10146e26.png)
Ref: https://konik.io/ZUGFeRD-Spezifikation/Das-ZUGFeRD-Format_1p0.pdf

**Comment by oledede** [comment]
This is where the problem arises.

We use the ConformanceLevel "Extended".


And it has to be like this:
<zf: version> 1.0 </ zf: version>

**Comment by oledede** [comment]
This is our area:

 <rdf:Description xmlns:zf="urn:ferd:pdfa:CrossIndustryDocument:invoice:1p0#" rdf:about="">
      <zf:DocumentType>INVOICE</zf:DocumentType>
      <zf:DocumentFileName>ZUGFeRD-invoice.xml</zf:DocumentFileName>
      <zf:ConformanceLevel>EXTENDED</zf:ConformanceLevel>
      <zf:Version>1p0</zf:Version>
    </rdf:Description>
  </rdf:RDF>



And this  <zf:Version>1p0</zf:Version> needs to be changed in  <zf:Version>1.0</zf:Version>.

**Comment by Vad1mo** [comment]
This is strange, as we normally write `<zf:Version>1.0</zf:Version>` Which Version of the Library are you using and what PDF Converter?

**Comment by oledede** [comment]
ZUGFeRD.NET 1.01.
IKVM 8.1.5717

Unfortunately, I can not find any other DLL's for .net

**Comment by oledede** [comment]
Can I get the latest DLL for C # / .net somewhere?

**Comment by oledede** [comment]
Kann man die aktuellsten bzw. DLL's bei denen dieses Problem nicht auftaucht bekommen?

**Comment by Vad1mo** [comment]
Try this one [ZUGFeRD.NET-1.3.1.dll](https://sonnenberg.myDS.me/sharing/Xed5ki9xj)  this should do it.
