### ISSUE TITLE
@ trade.items[0].settlement.monetarySummation.totalAllowanceCharge - Error

### ISSUE THREAD

**Issue by oledede** [konik-io/konik#70]
Hallo,
ich verwende die DLL in der Version 1.3.1 und bekomme nun folgende Meldung:

Invoice has (1) violations.
Berechneter Wert ist [-9.82] aber tatsächliche vorhander Wert ist [4.91] @ trade.items[1].settlement.monetarySummation.totalAllowanceCharge

Der Kunde hat einen Artikel mit der Menge 2 gekauft. Insgesamt bekommt er dann 9,82 € Rabatt. Was ja auch richtig wäre, doch warum ist der Wert mit einem - Vorzeichen und warum ist der andere Wert 4,91 €?

**Comment by oledede** [comment]
Dies ist nun ein anderer Fehler:

Invoice has (2) violations.
Berechneter Wert ist [-9.82] aber tatsächliche vorhander Wert ist [null] @ trade.items[1].settlement.monetarySummation.totalAllowanceCharge
Berechneter Wert ist [-10.22] aber tatsächliche vorhander Wert ist [null] @ trade.items[0].settlement.monetarySummation.totalAllowanceCharge

**Comment by Vad1mo** [comment]
kannst du die Rechnung zusenden oder hier posten?

**Comment by oledede** [comment]
![1Unbenannt](https://user-images.githubusercontent.com/46195058/55942458-b5415500-5c44-11e9-8bcd-4fb1dd41f885.PNG)

**Comment by oledede** [comment]
Gestern habe ich die DLL wie gesagt ausgetauscht, die hast du mir ja zur Verfügung gestellt.

Nun bekomme ich halt diese Fehlermeldungen...

**Comment by Vad1mo** [comment]
ich benötige das pdf und xml, du kannst es auch gerne per mail zusenden.

**Comment by oledede** [comment]
Am welche Adresse ?


Mit freundlichen Grüßen 
Simon Dadok
simondadok@aol.com


-----Ursprüngliche Mitteilung-----
Von: Vadim Bauer <notifications@github.com>
An: konik-io/konik <konik@noreply.github.com>
Cc: oledede <simondadok@aol.com>; Author <author@noreply.github.com>
Verschickt: Do, 11. Apr. 2019 10:32
Betreff: Re: [konik-io/konik] @ trade.items[0].settlement.monetarySummation.totalAllowanceCharge - Error (#70)

ich benötige das pdf und xml, du kannst es auch gerne per mail zusenden.—

**Comment by oledede** [comment]
An welche Adresse?

**Comment by oledede** [comment]
Hast eine Mail

**Comment by oledede** [comment]
Gibt es schon eine Lösung bzw einen Tipp?
