### ISSUE TITLE
Validation issue: Im Basic-Profil muss AssociatedDocumentLineDocument/SpecifiedSupplyChainTradeSettlement  leer gesendet werden.

### ISSUE THREAD

**Issue by macpock** [konik-io/konik#75]
Dear all,

thanks to Vadim I was able to get the official example project (coming with the konik stuff) up and running using the new zugferd DLL in its version 1.3.2 (ZUGFeRD.NET-1.3.2-SNAPSHOT.dll).

After validating (basic/comfort) the resulting Pdf (acme_invoice-42_ZUGFeRD.pdf)  https://www.din-zugferd-validation.org/ it returned (only) two errors:

1: Im Basic-Profil muss AssociatedDocumentLineDocument leer gesendet werden.
2: Im Basic-Profil muss SpecifiedSupplyChainTradeSettlement leer gesendet werden.

Pfa Screenshots plus src attached

Any idea to avoid them validation errors?

Regards, Mac

![2019-07-05 10_16_09-Validation Portal](https://user-images.githubusercontent.com/6705086/60709396-96372400-9f10-11e9-8062-b009917f29c6.png)
![2019-07-05 10_16_57-Validation Portal](https://user-images.githubusercontent.com/6705086/60709401-9a634180-9f10-11e9-9366-6145875d8bec.png)
[NetExampleInvoice.txt](https://github.com/konik-io/konik/files/3361823/NetExampleInvoice.txt)

**Comment by Vad1mo** [comment]
kannst du das XML hier anhängen?

**Comment by macpock** [comment]
hier ist schonmal die XML Datei … ich tue das im github auch noch hochladen

**Comment by macpock** [comment]
Hier die XML Datei

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><rsm:CrossIndustryDocument xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:15" xmlns:rsm="urn:ferd:CrossIndustryDocument:invoice:1p0"><rsm:SpecifiedExchangedDocumentContext><ram:GuidelineSpecifiedDocumentContextParameter><ram:ID>urn:ferd:CrossIndustryDocument:invoice:1p0:basic</ram:ID></ram:GuidelineSpecifiedDocumentContextParameter></rsm:SpecifiedExchangedDocumentContext><rsm:HeaderExchangedDocument><ram:ID>20131122-42</ram:ID><ram:Name>Rechnung</ram:Name><ram:TypeCode>380</ram:TypeCode><ram:IssueDateTime><udt:DateTimeString format="102">20190705</udt:DateTimeString></ram:IssueDateTime><ram:IncludedNote><ram:Content>MFG</ram:Content></ram:IncludedNote></rsm:HeaderExchangedDocument><rsm:SpecifiedSupplyChainTradeTransaction><ram:ApplicableSupplyChainTradeAgreement><ram:SellerTradeParty><ram:Name>Seller Inc.</ram:Name><ram:PostalTradeAddress><ram:PostcodeCode>80331</ram:PostcodeCode><ram:LineOne>Marienplatz 1</ram:LineOne><ram:CityName>München</ram:CityName><ram:CountryID>DE</ram:CountryID></ram:PostalTradeAddress><ram:SpecifiedTaxRegistration><ram:ID schemeID="FC">DE83700400410225355700</ram:ID></ram:SpecifiedTaxRegistration></ram:SellerTradeParty><ram:BuyerTradeParty><ram:Name>Buyer Inc.</ram:Name><ram:PostalTradeAddress><ram:PostcodeCode>50667</ram:PostcodeCode><ram:LineOne>Domkloster 4</ram:LineOne><ram:CityName>Köln</ram:CityName><ram:CountryID>DE</ram:CountryID></ram:PostalTradeAddress><ram:SpecifiedTaxRegistration><ram:ID schemeID="FC">DE83700400410225355700</ram:ID></ram:SpecifiedTaxRegistration></ram:BuyerTradeParty></ram:ApplicableSupplyChainTradeAgreement><ram:ApplicableSupplyChainTradeDelivery><ram:ActualDeliverySupplyChainEvent><ram:OccurrenceDateTime><udt:DateTimeString format="610">201908</udt:DateTimeString></ram:OccurrenceDateTime></ram:ActualDeliverySupplyChainEvent></ram:ApplicableSupplyChainTradeDelivery><ram:ApplicableSupplyChainTradeSettlement><ram:PaymentReference>20131122-42</ram:PaymentReference><ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode><ram:SpecifiedTradeSettlementPaymentMeans><ram:PayeePartyCreditorFinancialAccount><ram:IBANID>DE83700400410225355700</ram:IBANID></ram:PayeePartyCreditorFinancialAccount><ram:PayeeSpecifiedCreditorFinancialInstitution><ram:BICID>COBADEFFXXX</ram:BICID></ram:PayeeSpecifiedCreditorFinancialInstitution></ram:SpecifiedTradeSettlementPaymentMeans><ram:SpecifiedTradeSettlementMonetarySummation><ram:LineTotalAmount currencyID="EUR">100.00</ram:LineTotalAmount><ram:ChargeTotalAmount currencyID="EUR">0.00</ram:ChargeTotalAmount><ram:AllowanceTotalAmount currencyID="EUR">0.00</ram:AllowanceTotalAmount><ram:TaxBasisTotalAmount currencyID="EUR">100.00</ram:TaxBasisTotalAmount><ram:TaxTotalAmount currencyID="EUR">19.00</ram:TaxTotalAmount><ram:GrandTotalAmount currencyID="EUR">119.00</ram:GrandTotalAmount></ram:SpecifiedTradeSettlementMonetarySummation></ram:ApplicableSupplyChainTradeSettlement><ram:IncludedSupplyChainTradeLineItem><ram:SpecifiedSupplyChainTradeDelivery><ram:BilledQuantity unitCode="C62">1.0000</ram:BilledQuantity></ram:SpecifiedSupplyChainTradeDelivery><ram:SpecifiedTradeProduct><ram:Name>Saddle</ram:Name></ram:SpecifiedTradeProduct></ram:IncludedSupplyChainTradeLineItem></rsm:SpecifiedSupplyChainTradeTransaction></rsm:CrossIndustryDocument>
