### ISSUE TITLE
Preise und Zwischenwerte bei der Rabattberechnung müssen nach der ZUGFeRD-Vorgabe mit 4 Nachkommastellen angegeben werden.

### ISSUE THREAD

**Issue by oledede** [konik-io/konik#76]
Hallo,
gibt es schon eine Lösung für das Problem?

Ich habe nun alles versucht, aber es werden nach wie vor 4 Nachkommastellen gefordert.

<ram:BasisAmount currencyID="EUR">66.12</ram:BasisAmount>
--Preise und Zwischenwerte bei der Rabattberechnung müssen nach der ZUGFeRD-Vorgabe mit 4 Nachkommastellen angegeben werden.

**Comment by Vad1mo** [comment]
Es ist möglich die Nachkommastellen individuell anzupassen. 

> Preise und Zwischenwerte bei der Rabattberechnung müssen nach der ZUGFeRD-Vorgabe mit 4 Nachkommastellen angegeben werden.

https://konik.io/docs/index.html#konik_configuration

Es gibt in der ZUGFeRD Community da Uneinigkeiten, es nun 2 oder 4 sein sollen.

**Comment by oledede** [comment]
Hallo, 
es müssen laut Validierung 4 Stellen sein . Insofern laufen die Dateien leider nicht sauber durch.

**Comment by Vad1mo** [comment]
Wenn du die Nachkommastellen auf 4 stellst, wird es auch nicht funktionieren. Dann gibt es eine andere Fehlermeldung.

**Comment by Vad1mo** [comment]
Kannst du mal ein Beispiel XML hier posten dann gehen wir das durch.
