### ISSUE TITLE
exchange parts tax

### ISSUE THREAD

**Issue by Frogrek** [konik-io/konik#88]
Creating a invoice with the correct exchange parts tax in the position and in summary does not work.
Can you create a exemple how to do it correct?

**Comment by Vad1mo** [comment]
what is the error message or stacktrace?

**Comment by Frogrek** [comment]
GEFEG.FX Prüfung
********************
Prüf-Datum        	: 27.03.2020 10:58:34
Datei-Datum       	: 27.03.2020 10:58:33
Datei             	: RG670522_ZUGFeRD.PDF
Datei-Größe       	: 6.047 Bytes
Referenz-Standard 	: ZUGFeRD_comfort; 1.00

Notizen
******************************************************
ZUGFeRD (PDF-Metadaten) Typ: INVOICE
ZUGFeRD (PDF-Metadaten) Version: 1.0
ZUGFeRD (PDF-Metadaten) Profil: COMFORT
ZUGFeRD (PDF-Metadaten) Dateiname - OK
ZUGFeRD (PDF-Metadaten) - OK


(Zeilennummer) - Fehler / Hinweise 
******************************************************
(0131) Hinweis: Element 'ram:CalculatedAmount' wird im Comfort-Profil nicht ausgewertet.


Nachricht
******************************************************
(0001) <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
(0002) <rsm:CrossIndustryDocument xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:15" xmlns:rsm="urn:ferd:CrossIndustryDocument:invoice:1p0">
(0003)   <rsm:SpecifiedExchangedDocumentContext>
(0004)     <ram:GuidelineSpecifiedDocumentContextParameter>
(0005)       <ram:ID>urn:ferd:CrossIndustryDocument:invoice:1p0:comfort</ram:ID>
(0006)     </ram:GuidelineSpecifiedDocumentContextParameter>
(0007)   </rsm:SpecifiedExchangedDocumentContext>
(0008)   <rsm:HeaderExchangedDocument>
(0009)     <ram:ID>670522</ram:ID>
(0010)     <ram:Name>Rechnung</ram:Name>
(0011)     <ram:TypeCode>380</ram:TypeCode>
(0012)     <ram:IssueDateTime>
(0013)       <udt:DateTimeString format="102">20200327</udt:DateTimeString>
(0014)     </ram:IssueDateTime>
(0015)     <ram:IncludedNote>
(0016)       <ram:Content>Rechnung</ram:Content>
(0017)       <ram:SubjectCode>AAI</ram:SubjectCode>
(0018)     </ram:IncludedNote>
(0019)   </rsm:HeaderExchangedDocument>
(0020)   <rsm:SpecifiedSupplyChainTradeTransaction>
(0021)     <ram:ApplicableSupplyChainTradeAgreement>
(0022)       <ram:SellerTradeParty>
(0023)         <ram:Name>BODI-DATA GmbH</ram:Name>
(0024)         <ram:PostalTradeAddress>
(0025)           <ram:PostcodeCode>72348</ram:PostcodeCode>
(0026)           <ram:LineOne>Neue Burg 1</ram:LineOne>
(0027)           <ram:CityName>Rosenfeld</ram:CityName>
(0028)           <ram:CountryID>DE</ram:CountryID>
(0029)         </ram:PostalTradeAddress>
(0030)         <ram:SpecifiedTaxRegistration>
(0031)           <ram:ID schemeID="FC">456852951753</ram:ID>
(0032)         </ram:SpecifiedTaxRegistration>
(0033)       </ram:SellerTradeParty>
(0034)       <ram:BuyerTradeParty>
(0035)         <ram:Name>Matthias Mustermann</ram:Name>
(0036)         <ram:PostalTradeAddress>
(0037)           <ram:PostcodeCode>22222</ram:PostcodeCode>
(0038)           <ram:LineOne>Musterstrasse 88</ram:LineOne>
(0039)           <ram:CityName>Musterhausen</ram:CityName>
(0040)           <ram:CountryID>DE</ram:CountryID>
(0041)         </ram:PostalTradeAddress>
(0042)         <ram:SpecifiedTaxRegistration>
(0043)           <ram:ID schemeID="FC"></ram:ID>
(0044)         </ram:SpecifiedTaxRegistration>
(0045)       </ram:BuyerTradeParty>
(0046)     </ram:ApplicableSupplyChainTradeAgreement>
(0047)     <ram:ApplicableSupplyChainTradeDelivery>
(0048)       <ram:ActualDeliverySupplyChainEvent>
(0049)         <ram:OccurrenceDateTime>
(0050)           <udt:DateTimeString format="610">202004</udt:DateTimeString>
(0051)         </ram:OccurrenceDateTime>
(0052)       </ram:ActualDeliverySupplyChainEvent>
(0053)     </ram:ApplicableSupplyChainTradeDelivery>
(0054)     <ram:ApplicableSupplyChainTradeSettlement>
(0055)       <ram:PaymentReference>670522</ram:PaymentReference>
(0056)       <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
(0057)       <ram:SpecifiedTradeSettlementPaymentMeans>
(0058)         <ram:PayeePartyCreditorFinancialAccount>
(0059)           <ram:IBANID> DE56 6535 1260 0062 4001 12</ram:IBANID>
(0060)         </ram:PayeePartyCreditorFinancialAccount>
(0061)         <ram:PayeeSpecifiedCreditorFinancialInstitution>
(0062)           <ram:BICID>SOLADES1BAL</ram:BICID>
(0063)         </ram:PayeeSpecifiedCreditorFinancialInstitution>
(0064)       </ram:SpecifiedTradeSettlementPaymentMeans>
(0065)       <ram:ApplicableTradeTax>
(0066)         <ram:CalculatedAmount currencyID="EUR">45.60</ram:CalculatedAmount>
(0067)         <ram:TypeCode>VAT</ram:TypeCode>
(0068)         <ram:BasisAmount currencyID="EUR">240.00</ram:BasisAmount>
(0069)         <ram:CategoryCode>S</ram:CategoryCode>
(0070)         <ram:ApplicablePercent>19.00</ram:ApplicablePercent>
(0071)       </ram:ApplicableTradeTax>
(0072)       <ram:ApplicableTradeTax>
(0073)         <ram:CalculatedAmount currencyID="EUR">4.56</ram:CalculatedAmount>
(0074)         <ram:TypeCode>AAJ</ram:TypeCode>
(0075)         <ram:BasisAmount currencyID="EUR">24.00</ram:BasisAmount>
(0076)         <ram:CategoryCode>S</ram:CategoryCode>
(0077)         <ram:ApplicablePercent>19.00</ram:ApplicablePercent>
(0078)       </ram:ApplicableTradeTax>
(0079)       <ram:SpecifiedTradeAllowanceCharge>
(0080)         <ram:ChargeIndicator>
(0081)           <udt:Indicator>false</udt:Indicator>
(0082)         </ram:ChargeIndicator>
(0083)         <ram:ActualAmount currencyID="EUR">0.00</ram:ActualAmount>
(0084)         <ram:CategoryTradeTax>
(0085)           <ram:TypeCode>VAT</ram:TypeCode>
(0086)           <ram:CategoryCode>S</ram:CategoryCode>
(0087)           <ram:ApplicablePercent>19.00</ram:ApplicablePercent>
(0088)         </ram:CategoryTradeTax>
(0089)       </ram:SpecifiedTradeAllowanceCharge>
(0090)       <ram:SpecifiedTradeSettlementMonetarySummation>
(0091)         <ram:LineTotalAmount currencyID="EUR">240.00</ram:LineTotalAmount>
(0092)         <ram:ChargeTotalAmount currencyID="EUR">0.00</ram:ChargeTotalAmount>
(0093)         <ram:AllowanceTotalAmount currencyID="EUR">0.00</ram:AllowanceTotalAmount>
(0094)         <ram:TaxBasisTotalAmount currencyID="EUR">240.00</ram:TaxBasisTotalAmount>
(0095)         <ram:TaxTotalAmount currencyID="EUR">50.16</ram:TaxTotalAmount>
(0096)         <ram:GrandTotalAmount currencyID="EUR">290.16</ram:GrandTotalAmount>
(0097)         <ram:TotalPrepaidAmount currencyID="EUR">0.00</ram:TotalPrepaidAmount>
(0098)         <ram:DuePayableAmount currencyID="EUR">290.16</ram:DuePayableAmount>
(0099)       </ram:SpecifiedTradeSettlementMonetarySummation>
(0100)     </ram:ApplicableSupplyChainTradeSettlement>
(0101)     <ram:IncludedSupplyChainTradeLineItem>
(0102)       <ram:AssociatedDocumentLineDocument>
(0103)         <ram:LineID>1</ram:LineID>
(0104)       </ram:AssociatedDocumentLineDocument>
(0105)       <ram:SpecifiedSupplyChainTradeAgreement>
(0106)         <ram:GrossPriceProductTradePrice>
(0107)           <ram:ChargeAmount currencyID="EUR">240.0000</ram:ChargeAmount>
(0108)           <ram:BasisQuantity unitCode="C62">1.0000</ram:BasisQuantity>
(0109)           <ram:AppliedTradeAllowanceCharge>
(0110)             <ram:ChargeIndicator>
(0111)               <udt:Indicator>false</udt:Indicator>
(0112)             </ram:ChargeIndicator>
(0113)             <ram:ActualAmount currencyID="EUR">0.0000</ram:ActualAmount>
(0114)           </ram:AppliedTradeAllowanceCharge>
(0115)         </ram:GrossPriceProductTradePrice>
(0116)         <ram:NetPriceProductTradePrice>
(0117)           <ram:ChargeAmount currencyID="EUR">240.0000</ram:ChargeAmount>
(0118)           <ram:BasisQuantity unitCode="C62">1.0000</ram:BasisQuantity>
(0119)         </ram:NetPriceProductTradePrice>
(0120)       </ram:SpecifiedSupplyChainTradeAgreement>
(0121)       <ram:SpecifiedSupplyChainTradeDelivery>
(0122)         <ram:BilledQuantity unitCode="C62">1.0000</ram:BilledQuantity>
(0123)       </ram:SpecifiedSupplyChainTradeDelivery>
(0124)       <ram:SpecifiedSupplyChainTradeSettlement>
(0125)         <ram:ApplicableTradeTax>
(0126)           <ram:TypeCode>VAT</ram:TypeCode>
(0127)           <ram:CategoryCode>S</ram:CategoryCode>
(0128)           <ram:ApplicablePercent>19.00</ram:ApplicablePercent>
(0129)         </ram:ApplicableTradeTax>
(0130)         <ram:ApplicableTradeTax>
(0131)           <ram:CalculatedAmount currencyID="EUR">4.56</ram:CalculatedAmount>
(0132)           <ram:TypeCode>AAJ</ram:TypeCode>
(0133)           <ram:CategoryCode>S</ram:CategoryCode>
(0134)           <ram:ApplicablePercent>19.00</ram:ApplicablePercent>
(0135)         </ram:ApplicableTradeTax>
(0136)         <ram:SpecifiedTradeSettlementMonetarySummation>
(0137)           <ram:LineTotalAmount currencyID="EUR">240.00</ram:LineTotalAmount>
(0138)         </ram:SpecifiedTradeSettlementMonetarySummation>
(0139)       </ram:SpecifiedSupplyChainTradeSettlement>
(0140)       <ram:SpecifiedTradeProduct>
(0141)         <ram:SellerAssignedID>0986022151090</ram:SellerAssignedID>
(0142)         <ram:Name>STARTER</ram:Name>
(0143)       </ram:SpecifiedTradeProduct>
(0144)     </ram:IncludedSupplyChainTradeLineItem>
(0145)   </rsm:SpecifiedSupplyChainTradeTransaction>
(0146) </rsm:CrossIndustryDocument>

**Comment by Vad1mo** [comment]
closing is as its not a software bug. If you need help accomplishing your task contact support or ask the community.
