### ISSUE TITLE
ZUGFeRD 1.0 - Fehler bei LineTotal

### ISSUE THREAD

**Issue by SchwarzBeere** [konik-io/konik#95]
Hallo,

der Wert, den ich für MonetarySummation.LineTotalAmount übergebe wird durch TaxBasisTotalAmount ersetzt. 
Hat das Gründe oder liegt hier ein Bug vor?
Vielleicht wird es ja mir Version 2.x behoben...

VG SchwarzBeere

**Comment by Vad1mo** [comment]
Ist alles korrekt, können Sie ein Beispiel posten?

**Comment by SchwarzBeere** [comment]
Naja, ich übergebe: 

LineTotal                    250,00
AllowanceTotal            12,50 
ChargeTotal                   0,00 
TaxBasisTotal              237,50
TaxPercentage               19% 
TaxTotalAmount           45,125 
GrandTotal                 282,625 


und bekomme: 
(0095)       <ram:SpecifiedTradeSettlementMonetarySummation>
(0096)         <ram:LineTotalAmount currencyID="EUR">237.5</ram:LineTotalAmount>
(0097)         <ram:ChargeTotalAmount currencyID="EUR">0</ram:ChargeTotalAmount>
(0098)         <ram:AllowanceTotalAmount currencyID="EUR">12.5</ram:AllowanceTotalAmount>
(0099)         <ram:TaxBasisTotalAmount currencyID="EUR">237.5</ram:TaxBasisTotalAmount>
(0100)         <ram:TaxTotalAmount currencyID="EUR">45.12</ram:TaxTotalAmount>
(0101)         <ram:GrandTotalAmount currencyID="EUR">282.62</ram:GrandTotalAmount>
(0103)       </ram:SpecifiedTradeSettlementMonetarySummation>

Reicht das fürs Verständnis?

Außerdem bemängelt die Prüfsoftware, das die Beträge und Prozentzahlen nicht mit den geforderten 2 Nachkommastellen / und Mengen nicht mit den geforderten 4 Nachkommastellen übergeben werden.


Ach ja, ich versuche mit .Net eine DLL zur Anbindung an VBA zu bauen.

**Comment by Vad1mo** [comment]
Welche Version von .NET haben sie?

**Comment by Vad1mo** [comment]
Anbei die aktuelle Version: [ZUGFeRD.NET-1.3.2](https://www.dropbox.com/s/s4g1s0j1bt2iadm/ZUGFeRD.NET-1.3.2-NuGet.zip?dl=1)

**Comment by SchwarzBeere** [comment]
.net framework 4.6.1

**Comment by SchwarzBeere** [comment]
ich kapituliere

mit der alten Version habe ich wenigstens eine unkorrekte PDF mit XML erzeugt. Jetzt gar keine mehr. 

Ich arbeite in VisualStudio 2019. 
Ich habe die Verweise zur alten Zugferd.Dll gelöscht, die neue hinzugefügt. Das gleiche mit den ganzen IKVM-DLLs weil die neue Zugferd.DLL auf eine aktuellere Version verweist. 
Alles sieht toll aus, kein Fehler wird gemeldet, meine neue DLL wird erstellt, 
Und dann wird doch keine PDF mit XML erstellt. 

Access VBA bringt folgenden Fehler:  
Fehler: -2147024894
Die Datei oder Assembly "ZUGFeRD.NET-1.3.2-SNAPSHOT, Version=1.3.2.0, Culture=neutral, PublicKeyToken=ff86d12d3bcaf7de" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.

Der Fehler tritt  bei der Übergabe von Codes (Ländercode, SteuernummerCode) auf -die hab ich alle auskommentiert- ,  und dann nochmal allgemein beim Rechnung erstellen. 

Vielleicht können sie was mit dem Fehler anfangen. Aber die Identität wird doch so von VS festgelegt. ..

Schönen Abend

**Comment by Vad1mo** [comment]
Dies habe ich schon mal gesehen. 

ka. warum, aber ändern Sie den Namen der DLL auf **ZUGFeRD.NET-1.3.2-SNAPSHOT**  das sollte dann klappen.

**Comment by SchwarzBeere** [comment]
und da soll einer draufkommen...

Vielen Dank, jetzt läufts zumindest wieder. 
Das Problem mit LineTotal und TaxBasisTotal habe ich leider immer noch. (in LineTotal wird TaxBasisTotal übergeben)
Summen, Steuersätze und Mengen werden jetzt aber korrekt formatiert ausgegeben. 

Ich kann keine Preise zu den einzelnen Artikeln einfügen 
und  die fehlenden Elemente 
ApplicableSupplyChainTradeDelivery &  AssociatedDocumentLineDocument
werden angemahnt. 

Vielleicht bekomme ich dazu noch einen Tipp ;-)

**Comment by Vad1mo** [comment]
Es ist so, 

wenn man alles berechnen lässt dann sollte, man nur die Eingangswerte setzten. 
Wenn man die Summary setzt, dann sollte man nicht berechnen. 

 Von hier aus kann ich nicht sagen ohne XML oder Code.

**Comment by SchwarzBeere** [comment]
... das mit der LineTotal war mein dummer und total peinlicher Kopierfehler...

**Comment by Vad1mo** [comment]
freut mich das es alles geklappt hat

**Comment by SchwarzBeere** [comment]
Ja, vielen Dank für die schnelle Hilfe.Viele GrüßeJana MeinelSchillerstraße 18 - 08223 Falkenstein - 0178 3567570*Diese Nachricht wurde mit einem Smartphone gesendet. Sollte diese Nachricht sowohl orthographisch und grammatikalisch korrekt als auch verständlich sein, ist das reiner Zufall und nicht auf die Verwendung einer bestimmten Smartphonemarke zurückzuführen.Am 12.11.2020 22:02 schrieb Vadim Bauer <notifications@github.com>:
freut mich das es alles geklappt hat
